config/routes.rb
Cems::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :template_questions

  namespace :api, defaults: { format: :json } do
    resources :personal_engagement_lists, only: [:new, :create, :edit, :update] do
      get '/lists' => 'personal_engagement_lists#pels_for_current_user', on: :collection
    end

    resources :requests, only: [:new, :create, :update] do
      get 'all' => 'requests#all_for_current_user', on: :collection
      match 'submit' => 'requests#submit_requisition', on: :member, via: [:put, :patch]
    end
  end

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/ }

  get '/signout' => "application#signout"
  get '/health'   => "application#health"

  root 'home#index'
end

app/views/templates/dashboard.html.erb
<div ng-cloak ng-init="init()" fade-animation="true">
  <h3>Welcome to your Dashboard</h3>

  <ul class="list-group">
    <li ng-repeat="pel in pels | orderBy:'-created_at'" class="list-group-item">
      <h5>
        Created Date: {{pel.created_at | date:'mediumDate'}}
        <small>(id: {{pel.id}})</small>
        <span class="label label-success" ng-show="isNew(pel)">new!</span>
      </h5>
      <ol><li ng-repeat="question in pel.questions | orderBy:'priority'">
        <p>{{question.body}} (Score: {{question.score}})<p>
      </li></ol>
  
      <div class="btn-group btn-group-xs pull-right">
        <button class="btn btn-default" ng-click="edit(pel.id)">Edit</button>
        <button class="btn btn-default disabled">Make a Copy</button>
      </div><br>
    </li>
  </ul>

  <button class="btn btn-default btn-sm pull-right" ng-click="new()">
    Create New Personal Engagement List
  </button>
<div>

app/views/templates/header_menu.html.erb
<div class="container">
  <div class="row" ng-controller="MenuController">
    <nav class="navbar navbar-default" role="navigation">
      <!-- Toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-text">AVATAR</span>
        <span class="navbar-text"><%= current_user.enterprise_id %></span>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Dashboard', root_path %></li>
          <li>
            <a href= <%= "#{root_url}#/inbox" %> >
              Inbox <span ng-show="messageCount > 0" class="badge orangeBadge">{{messageCount}}</span>
            </a>
          </li>
          <% if can? :manage, Request %>
            <li class="dropdown">
              <a href="" class="dropdown-toggle" data-toggle="dropdown">Requests <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Create New Request', "#{root_url}#/new_request" %></li>
              </ul>
            </li>
          <% end %>
          <% if can? :manage, TemplateQuestion %>
            <li class="dropdown">
              <a href="" class="dropdown-toggle" data-toggle="dropdown">Administration <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Template Questions', template_questions_path %></li>
                <li class="divider"></li>
                <li class="disabled"><a href="#">Manage Roles</a></li>
              </ul>
            </li>
          <% end %>
          <li><%= link_to 'Sign Out', signout_path %></li>
        </ul>
      </div>
    </nav>
  </div>
</div>