config/routes.rb
Cems::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :template_questions

  namespace :api, defaults: { format: :json } do
    resources :personal_engagement_lists, only: [:new, :create, :edit, :update] do
      get '/lists' => 'personal_engagement_lists#pels_for_current_user', on: :collection
    end

    resources :requests, only: [:new, :create, :update] do
      get 'all' => 'requests#all_for_current_user', on: :collection
      match 'submit' => 'requests#submit_requisition', on: :member, via: [:put, :patch]
    end
  end

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/ }

  get '/signout' => "application#signout"
  get '/health'   => "application#health"

  root 'home#index'
end

app/models/template_question.rb
class TemplateQuestion < ActiveRecord::Base
  validates :body, presence: true
end

app/controllers/template_questions_controller.rb
class TemplateQuestionsController < ApplicationController
  before_action :set_template_question, only: [:edit, :update, :destroy]
  before_action :create_template_question, only: :create # Workaround to a known bug of CanCan and StrongParams
  load_and_authorize_resource

  def index
    @template_questions = TemplateQuestion.all
  end

  def new
    @template_question = TemplateQuestion.new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @template_question.save
        format.html { redirect_to template_questions_path, notice: 'Template question was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @template_question.update(template_question_params)
        format.html { redirect_to template_questions_path, notice: 'Template question was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @template_question.destroy
    respond_to do |format|
      format.html { redirect_to template_questions_url }
    end
  end

  private
  def create_template_question
    @template_question = TemplateQuestion.new(template_question_params)
  end

  def set_template_question
    @template_question = TemplateQuestion.find(params[:id])
  end

  def template_question_params
    params.require(:template_question).permit(:body)
  end
end

app/views/template_questions/_form.html.erb
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <%= form_for(@template_question) do |f| %>
    <% if @template_question.errors.any? %>
      <div class="alert alert-danger">
        <h5>
          <%= pluralize(@template_question.errors.count, "error") %> prohibited this question from being saved:
        </h5>

        <ul>
          <% @template_question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul><br>
      </div>
    <% end %>

    <div class="panel panel-default col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="panel-body">
        <br>
        <div class="input-group">
          <span class="input-group-addon">Body</span>
          <%= f.text_field :body, class: "form-control", placeholder: "goes here..." %>
        </div><br>

        <div class="pull-right">
          <%= f.submit 'Create', class: "btn btn-sm btn-success" %>
          <%= link_to 'Cancel', template_questions_path, class: "btn btn-sm btn-default" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/template_questions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h3>Template Questions <small>Manage the list of areas for Personal Engagement Lists</small></h3>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/views/template_questions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h3>Template Questions <small>Manage the list of areas for Personal Engagement Lists</small></h3>
    </div>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <ul class="list-group">
        <% @template_questions.each do |template_question| %>
          <li class="list-group-item">
            <p class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
              <%= template_question.body %>
            </p>
            <div class="btn-group btn-group-xs pull-right">
              <%= link_to 'Edit', edit_template_question_path(template_question), class: "btn btn-default" %>
              <%= link_to 'Delete', template_question, method: :delete, data: { confirm: 'Are you sure you want to delete this template question?' }, class: "btn btn-danger" %>
            </div><br>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <%= link_to 'Create New Template Question', new_template_question_path, class: "btn btn-sm btn-default" %>
    </div>
  </div>
</div>

app/views/template_questions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h3>Template Questions <small>Manage the list of areas for Personal Engagement Lists</small></h3>
    </div>

    <%= render 'form' %>
  </div>
</div>